### ISSUE TITLE
note: optimized static rust binaries

### ISSUE THREAD

**Issue by thetredev** [thetredev/advent-of-code-2023#2]
```toml
# ./.cargo/config

[build]
rustflags = ["-C", "link-arg=-s"]
target = ["x86_64-unknown-linux-musl"]
```

```toml
# ./Cargo.toml

[package]
name = "rust-app"
version = "0.1.0"
authors = ["me <me@me.me>"]

[[bin]]
name = "main"

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
```

```rust
// ./src/bin/main.rs

fn ...
```

```
$ cargo build --release
```
